#!/usr/bin/env python3
"""Regenerate assets/telemetry.svg from live GitHub API data.

No fabricated numbers: every value shown is computed from
https://api.github.com/users/{USER}/repos at build time.

Stdlib only. Exits non-zero on failure so CI turns red instead of
rendering stale-but-plausible data.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.request
from datetime import date, datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

USER = os.environ.get("TELEMETRY_USER", "anujsingh-cse")
OUT = Path(__file__).resolve().parent.parent / "assets" / "telemetry.svg"
API = f"https://api.github.com/users/{USER}/repos?per_page=100&sort=updated"


def fetch_repos() -> list[dict]:
    req = urllib.request.Request(
        API,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "skeptic-os-telemetry",
            **({"Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}"} if os.environ.get("GITHUB_TOKEN") else {}),
        },
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        data = json.load(r)
    if not isinstance(data, list) or not data:
        raise RuntimeError("unexpected API payload")
    return data


def build_facts(repos: list[dict]) -> list[tuple[str, str]]:
    total = len(repos)
    originals = sum(1 for r in repos if not r["fork"])

    newest = max(
        [r for r in repos if not r["fork"] and r["name"] != USER],
        key=lambda r: r["created_at"],
    )
    freshest = max(repos, key=lambda r: r["pushed_at"])
    first = min(repos, key=lambda r: r["created_at"])

    created = datetime.fromisoformat(first["created_at"].replace("Z", "+00:00")).date()
    uptime_days = (datetime.now(timezone.utc).date() - created).days

    pushed = datetime.fromisoformat(freshest["pushed_at"].replace("Z", "+00:00")).date().isoformat()
    born = datetime.fromisoformat(newest["created_at"].replace("Z", "+00:00")).date().isoformat()

    return [
        ("REPOS TRACKED", f"{total} public / {originals} original"),
        ("LAST SIGNAL", f"{freshest['name']} @ {pushed}"),
        ("NEWEST EXPERIMENT", f"{newest['name']} @ {born}"),
        ("RUNNING SINCE", f"{created.isoformat()} ({uptime_days} days)"),
    ]


def render_svg(facts: list[tuple[str, str]]) -> str:
    today = date.today().isoformat()
    lines = []
    y = 46
    for label, value in facts:
        lines.append(
            f'<text x="24" y="{y}" class="dim">{escape(label)}</text>'
            f'<text x="212" y="{y}" class="fg">{escape(value)}</text>'
        )
        y += 22
    rows = "\n    ".join(lines)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="700" height="190" viewBox="0 0 700 190" role="img" aria-label="live telemetry">
  <style>
    text {{ font: 12.5px ui-monospace, SFMono-Regular, Consolas, monospace; }}
    .fg {{ fill: #24292f; }}
    .dim {{ fill: #6e7781; }}
    .ok {{ fill: #1a7f37; }}
    @media (prefers-color-scheme: dark) {{
      .fg {{ fill: #e6edf3; }}
      .dim {{ fill: #7d8590; }}
      .ok {{ fill: #3fb950; }}
    }}
  </style>
  <rect x="0.5" y="0.5" width="699" height="189" rx="8" fill="none" class="fg" stroke-opacity="0.25" stroke="#8b949e"/>
  <circle cx="18" cy="20" r="4" class="ok">
    <animate attributeName="opacity" values="1;0.25;1" dur="2s" repeatCount="indefinite"/>
  </circle>
  <text x="32" y="24" class="fg">LIVE TELEMETRY</text>
  <text x="676" y="24" text-anchor="end" class="dim">source: github api · ci {escape(today)}</text>
  <line x1="16" y1="34" x2="684" y2="34" stroke="#8b949e" stroke-opacity="0.3"/>
  {rows}
  <text x="24" y="{y + 8}" class="dim">numbers move because reality moves · regenerated by .github/workflows/telemetry.yml</text>
</svg>
"""


def main() -> int:
    try:
        facts = build_facts(fetch_repos())
        svg = render_svg(facts)
    except Exception as e:  # noqa: BLE001 - fail loudly, ship nothing stale
        print(f"telemetry: fetch/render failed: {e}", file=sys.stderr)
        return 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(svg, encoding="utf-8")
    print(f"telemetry: wrote {OUT} ({len(svg)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
